book_url: "https://www.railstutorial.org/book"
tutorial_url: "https://www.railstutorial.org/"
rails_tutorial_book_text: "Rails Tutorial book"
ror_tutorial_text: "Ruby on Rails Tutorial"

mailer:
  email_from_address: "noreply@example.com"
  mailer_layout: "mailer"

host: "http://localhost:3000"
