book_url: "https://www.railstutorial.org/book"
tutorial_url: "https://www.railstutorial.org/"
rails_tutorial_book_text: "Rails Tutorial book"
ror_tutorial_text: "Ruby on Rails Tutorial"

mailer:
  email_from_address: "noreply@example.com"
  mailer_layout: "mailer"

host: "http://localhost:3000"

digit_50: 50
digit_30: 30

microposts:
  image_content_types:
    - image/jpeg
    - image/gif
    - image/png
  image_accept_format: "image/jpeg,image/gif,image/png"
